# Configuration centralisée pour la pipeline de traduction/analyse


# Dossiers principaux
raw_data_dir: data/raw
processed_data_dir: data/processed
batches_dir: translations/batches
meta_dir: translations/meta
logs_dir: logs
models_dir: models
examples_dir: examples
scripts_dir: scripts
tests_dir: tests
pipeline_dir: pipeline
utils_dir: utils


# Modèles à tester (ajoute ici tous les modèles que tu veux comparer)
models:
  - name: opus-mt-en-fr
    path: opus-mt-en-fr/models--Helsinki-NLP--opus-mt-en-fr/snapshots/dd7f6540a7a48a7f4db59e5c0b9c42c8eea67f18
    type: marian
  # - name: nllb-200
  #   path: models/nllb-200
  #   type: nllb

# Paramètres de traitement
batch_size: 32
max_length: 256
num_workers: 2

device: cpu  # ou 'cpu' selon la machine

# Options pipeline
save_intermediate: true
log_level: INFO


# Pour l'analyse/statistiques
analysis_dir: analysis/results
analysis_scripts_dir: analysis/scripts



# Pour l'archivage automatique
archive_old_batches: true
archive_dir: archive



# Pour la gestion de l'état des lots
status_values: [en_attente, en_cours, termine, erreur]



# Pour la reproductibilité
random_seed: 42
