[project]
name = "trans_sent"
version = "0.1.0"
dependencies = [
    "torch==2.6.0",
    "transformers",
    "spacy",
    "sentencepiece>=0.2.1",
    "pandas>=2.3.1",
    "tabulate>=0.9.0",
    "matplotlib>=3.10.5",
    "pyyaml>=6.0.2",
]
